# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addtable.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 782)
        MainWindow.setMinimumSize(QtCore.QSize(735, 782))
        MainWindow.setMaximumSize(QtCore.QSize(735, 782))
        font = QtGui.QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setVerticalSpacing(13)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setMaximumSize(QtCore.QSize(173, 29))
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout_2.addWidget(self.cancel_button, 2, 1, 1, 1)
        self.add_menu_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_menu_button.setMaximumSize(QtCore.QSize(173, 29))
        self.add_menu_button.setObjectName("add_menu_button")
        self.gridLayout_2.addWidget(self.add_menu_button, 0, 1, 1, 1)
        self.add_table_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_table_button.setMinimumSize(QtCore.QSize(0, 60))
        self.add_table_button.setObjectName("add_table_button")
        self.gridLayout_2.addWidget(self.add_table_button, 0, 2, 3, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 8, 2, 2, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.table_name_lineedit = QtWidgets.QLineEdit(self.centralwidget)
        self.table_name_lineedit.setMinimumSize(QtCore.QSize(0, 30))
        self.table_name_lineedit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.table_name_lineedit.setFont(font)
        self.table_name_lineedit.setText("")
        self.table_name_lineedit.setObjectName("table_name_lineedit")
        self.gridLayout.addWidget(self.table_name_lineedit, 1, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.result_table = QtWidgets.QTableView(self.centralwidget)
        self.result_table.setObjectName("result_table")
        self.gridLayout.addWidget(self.result_table, 5, 2, 1, 1)
        self.menu_table = QtWidgets.QTableView(self.centralwidget)
        self.menu_table.setMinimumSize(QtCore.QSize(250, 0))
        self.menu_table.setMaximumSize(QtCore.QSize(300, 16777215))
        self.menu_table.setObjectName("menu_table")
        self.gridLayout.addWidget(self.menu_table, 5, 0, 1, 1)
        self.person_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.person_spinBox.setMinimumSize(QtCore.QSize(0, 30))
        self.person_spinBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.person_spinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.person_spinBox.setMinimum(1)
        self.person_spinBox.setObjectName("person_spinBox")
        self.gridLayout.addWidget(self.person_spinBox, 3, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 10, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.quantity_spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.quantity_spinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.quantity_spinBox.setMinimum(1)
        self.quantity_spinBox.setObjectName("quantity_spinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.quantity_spinBox)
        self.gridLayout.addLayout(self.formLayout, 8, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Add Table"))
        self.cancel_button.setText(_translate("MainWindow", "ยกเลิก"))
        self.add_menu_button.setText(_translate("MainWindow", "เพิ่มเมนู"))
        self.add_table_button.setText(_translate("MainWindow", "เพิ่มโต๊ะ"))
        self.label.setText(_translate("MainWindow", "ชื่อโต๊ะ / เลขโต๊ะ"))
        self.label_2.setText(_translate("MainWindow", "เมนูอาหาร"))
        self.label_3.setText(_translate("MainWindow", "จำนวนคน"))
        self.label_4.setText(_translate("MainWindow", "จำนวนจานที่ต้องการ :"))
