# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check_bill.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(419, 695)
        Dialog.setMinimumSize(QtCore.QSize(419, 695))
        font = QtGui.QFont()
        font.setPointSize(10)
        Dialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 6, 0, 1, 2)
        self.check_bill_button = QtWidgets.QPushButton(Dialog)
        self.check_bill_button.setMinimumSize(QtCore.QSize(0, 35))
        self.check_bill_button.setObjectName("check_bill_button")
        self.gridLayout.addWidget(self.check_bill_button, 11, 0, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        self.cancel_button.setMinimumSize(QtCore.QSize(0, 35))
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 11, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.total_price_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.total_price_label.setFont(font)
        self.total_price_label.setObjectName("total_price_label")
        self.gridLayout.addWidget(self.total_price_label, 8, 1, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 7, 0, 1, 2)
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 9, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(30)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.table_name = QtWidgets.QLabel(Dialog)
        self.table_name.setObjectName("table_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.table_name)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.person = QtWidgets.QLabel(Dialog)
        self.person.setObjectName("person")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.person)
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.in_time = QtWidgets.QLabel(Dialog)
        self.in_time.setObjectName("in_time")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.in_time)
        self.label_8 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.type = QtWidgets.QLabel(Dialog)
        self.type.setObjectName("type")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.type)
        self.gridLayout.addLayout(self.formLayout, 3, 0, 1, 2)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 10, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "ตรวจสอบรายการอาหาร"))
        self.label.setText(_translate("Dialog", "สรุปรายการอาหาร"))
        self.check_bill_button.setText(_translate("Dialog", "จ่ายเงิน"))
        self.cancel_button.setText(_translate("Dialog", "ยกเลิก"))
        self.label_5.setText(_translate("Dialog", "ราคาทั้งหมด :"))
        self.total_price_label.setText(_translate("Dialog", "0.0"))
        self.label_3.setText(_translate("Dialog", "เมนูอาหารทั้งหมด"))
        self.label_2.setText(_translate("Dialog", "ชื่อโต๊ะอาหาร / เลขโต๊ะอาหาร"))
        self.table_name.setText(_translate("Dialog", "0"))
        self.label_4.setText(_translate("Dialog", "จำนวนคน"))
        self.person.setText(_translate("Dialog", "0"))
        self.label_6.setText(_translate("Dialog", "เวลาเข้า"))
        self.in_time.setText(_translate("Dialog", "0"))
        self.label_8.setText(_translate("Dialog", "ประเภท"))
        self.type.setText(_translate("Dialog", "0"))
        self.label_7.setText(_translate("Dialog", "เมื่อลูกจ่ายเงินแล้วกรุณาคลิกจ่ายเงิน เพื่อยืนยันการชำระเงิน"))
        self.label_9.setText(_translate("Dialog", "ตรวจสอบความถูกต้องก่อนให้ลูกค้าชำระเงิน"))
