# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_windows.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(904, 731)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(904, 700))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(20, -1, 20, -1)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.person = QtWidgets.QLabel(self.centralwidget)
        self.person.setMinimumSize(QtCore.QSize(198, 40))
        self.person.setMaximumSize(QtCore.QSize(238, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.person.setFont(font)
        self.person.setTextFormat(QtCore.Qt.PlainText)
        self.person.setObjectName("person")
        self.verticalLayout.addWidget(self.person)
        self.type = QtWidgets.QLabel(self.centralwidget)
        self.type.setMinimumSize(QtCore.QSize(0, 40))
        self.type.setMaximumSize(QtCore.QSize(238, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.type.setFont(font)
        self.type.setTextFormat(QtCore.Qt.PlainText)
        self.type.setObjectName("type")
        self.verticalLayout.addWidget(self.type)
        self.timeleft = QtWidgets.QLabel(self.centralwidget)
        self.timeleft.setMinimumSize(QtCore.QSize(0, 40))
        self.timeleft.setMaximumSize(QtCore.QSize(238, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timeleft.setFont(font)
        self.timeleft.setTextFormat(QtCore.Qt.PlainText)
        self.timeleft.setObjectName("timeleft")
        self.verticalLayout.addWidget(self.timeleft)
        self.timein = QtWidgets.QLabel(self.centralwidget)
        self.timein.setMinimumSize(QtCore.QSize(0, 40))
        self.timein.setMaximumSize(QtCore.QSize(238, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.timein.setFont(font)
        self.timein.setTextFormat(QtCore.Qt.PlainText)
        self.timein.setObjectName("timein")
        self.verticalLayout.addWidget(self.timein)
        self.order_num = QtWidgets.QLabel(self.centralwidget)
        self.order_num.setMinimumSize(QtCore.QSize(0, 40))
        self.order_num.setMaximumSize(QtCore.QSize(238, 60))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.order_num.setFont(font)
        self.order_num.setTextFormat(QtCore.Qt.PlainText)
        self.order_num.setObjectName("order_num")
        self.verticalLayout.addWidget(self.order_num)
        self.total_price = QtWidgets.QLabel(self.centralwidget)
        self.total_price.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.total_price.setFont(font)
        self.total_price.setObjectName("total_price")
        self.verticalLayout.addWidget(self.total_price)
        self.gridLayout.addLayout(self.verticalLayout, 3, 1, 1, 1)
        self.table_no = QtWidgets.QLabel(self.centralwidget)
        self.table_no.setMinimumSize(QtCore.QSize(220, 62))
        self.table_no.setMaximumSize(QtCore.QSize(400, 62))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.table_no.setFont(font)
        self.table_no.setObjectName("table_no")
        self.gridLayout.addWidget(self.table_no, 1, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 1, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setMinimumSize(QtCore.QSize(0, 100))
        self.tableView.setMaximumSize(QtCore.QSize(3000, 1000))
        self.tableView.setSizeIncrement(QtCore.QSize(0, 0))
        self.tableView.setBaseSize(QtCore.QSize(0, 0))
        self.tableView.setObjectName("tableView")
        self.tableView.verticalHeader().setDefaultSectionSize(35)
        self.gridLayout.addWidget(self.tableView, 1, 0, 7, 1)
        self.tableName = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableName.sizePolicy().hasHeightForWidth())
        self.tableName.setSizePolicy(sizePolicy)
        self.tableName.setMinimumSize(QtCore.QSize(621, 40))
        self.tableName.setMaximumSize(QtCore.QSize(621, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.tableName.setFont(font)
        self.tableName.setTextFormat(QtCore.Qt.AutoText)
        self.tableName.setObjectName("tableName")
        self.gridLayout.addWidget(self.tableName, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 30, -1, -1)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.add_table_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_table_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.add_table_button.setFont(font)
        self.add_table_button.setObjectName("add_table_button")
        self.verticalLayout_2.addWidget(self.add_table_button)
        self.cancel_button = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_button.setEnabled(False)
        self.cancel_button.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_button.setFont(font)
        self.cancel_button.setObjectName("cancel_button")
        self.verticalLayout_2.addWidget(self.cancel_button)
        self.check_bill = QtWidgets.QPushButton(self.centralwidget)
        self.check_bill.setEnabled(False)
        self.check_bill.setMinimumSize(QtCore.QSize(0, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.check_bill.setFont(font)
        self.check_bill.setObjectName("check_bill")
        self.verticalLayout_2.addWidget(self.check_bill)
        self.gridLayout.addLayout(self.verticalLayout_2, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 904, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuTable = QtWidgets.QMenu(self.menubar)
        self.menuTable.setObjectName("menuTable")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAdd_Menu = QtWidgets.QAction(MainWindow)
        self.actionAdd_Menu.setObjectName("actionAdd_Menu")
        self.actionEdit_Menu = QtWidgets.QAction(MainWindow)
        self.actionEdit_Menu.setObjectName("actionEdit_Menu")
        self.actionSignout = QtWidgets.QAction(MainWindow)
        self.actionSignout.setObjectName("actionSignout")
        self.addmenu_action = QtWidgets.QAction(MainWindow)
        self.addmenu_action.setObjectName("addmenu_action")
        self.cancelmenu_action = QtWidgets.QAction(MainWindow)
        self.cancelmenu_action.setEnabled(False)
        self.cancelmenu_action.setObjectName("cancelmenu_action")
        self.refresh_action = QtWidgets.QAction(MainWindow)
        self.refresh_action.setShortcutVisibleInContextMenu(True)
        self.refresh_action.setObjectName("refresh_action")
        self.actionEditRest = QtWidgets.QAction(MainWindow)
        self.actionEditRest.setObjectName("actionEditRest")
        self.actionMenu = QtWidgets.QAction(MainWindow)
        self.actionMenu.setObjectName("actionMenu")
        self.actionCal = QtWidgets.QAction(MainWindow)
        self.actionCal.setEnabled(False)
        self.actionCal.setObjectName("actionCal")
        self.actionHistory = QtWidgets.QAction(MainWindow)
        self.actionHistory.setObjectName("actionHistory")
        self.actionResult = QtWidgets.QAction(MainWindow)
        self.actionResult.setObjectName("actionResult")
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionEditRest)
        self.menuFile.addAction(self.actionSignout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuMenu.addAction(self.actionAdd_Menu)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.actionMenu)
        self.menuTable.addAction(self.addmenu_action)
        self.menuTable.addAction(self.cancelmenu_action)
        self.menuTable.addAction(self.actionCal)
        self.menuTable.addSeparator()
        self.menuTable.addAction(self.refresh_action)
        self.menuTable.addSeparator()
        self.menuTable.addAction(self.actionHistory)
        self.menuTable.addAction(self.actionResult)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuTable.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Restaurant"))
        self.person.setText(_translate("MainWindow", "จำนวนคน :"))
        self.type.setText(_translate("MainWindow", "ประเภท :"))
        self.timeleft.setText(_translate("MainWindow", "เวลาที่เหลือ :"))
        self.timein.setText(_translate("MainWindow", "เวลาเข้า :"))
        self.order_num.setText(_translate("MainWindow", "จำนวนเมนูอาหาร :"))
        self.total_price.setText(_translate("MainWindow", "ราคาอาหารมื้อนี้ :"))
        self.table_no.setText(_translate("MainWindow", "A1"))
        self.tableName.setText(_translate("MainWindow", "RESTAURANT NAME"))
        self.add_table_button.setText(_translate("MainWindow", "เพิ่มโต๊ะอาหาร"))
        self.cancel_button.setText(_translate("MainWindow", "ยกเลิกรายการ"))
        self.check_bill.setText(_translate("MainWindow", "คิดเงิน"))
        self.menuFile.setTitle(_translate("MainWindow", "ไฟล์"))
        self.menuHelp.setTitle(_translate("MainWindow", "ช่วยเหลือ"))
        self.menuMenu.setTitle(_translate("MainWindow", "เมนูอาหาร"))
        self.menuTable.setTitle(_translate("MainWindow", "จัดการโต๊ะ"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionSettings.setText(_translate("MainWindow", "ตั้งค่า"))
        self.actionSettings.setShortcut(_translate("MainWindow", "Ctrl+,"))
        self.actionQuit.setText(_translate("MainWindow", "ออกจากโปรแกรม"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionHelp.setText(_translate("MainWindow", "ช่วยเหลือ"))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1"))
        self.actionAbout.setText(_translate("MainWindow", "เกี่ยวกับ Restaurant Management"))
        self.actionAdd_Menu.setText(_translate("MainWindow", "เพิ่มเมนูอาหาร"))
        self.actionEdit_Menu.setText(_translate("MainWindow", "แก้ไขเมนูอาหาร"))
        self.actionSignout.setText(_translate("MainWindow", "ลงชื่อออก"))
        self.addmenu_action.setText(_translate("MainWindow", "เพิ่มโต๊ะอาหาร"))
        self.cancelmenu_action.setText(_translate("MainWindow", "ยกเลิกรายการ"))
        self.refresh_action.setText(_translate("MainWindow", "รีเฟรช"))
        self.refresh_action.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionEditRest.setText(_translate("MainWindow", "แก้ข้อมูลร้าน"))
        self.actionMenu.setText(_translate("MainWindow", "เมนูอาหาร"))
        self.actionCal.setText(_translate("MainWindow", "คิดเงินรายการ"))
        self.actionHistory.setText(_translate("MainWindow", "ประวัติลูกค้า"))
        self.actionResult.setText(_translate("MainWindow", "สรุปยอดขาย"))
